{{- if .Values.tei.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ template "milvus.fullname" . }}-tei-headless
  labels:
    app: {{ template "milvus.name" . }}
    chart: {{ template "milvus.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
    component: text-embeddings-inference
    {{- if .Values.tei.service.labels }}
{{ toYaml .Values.tei.service.labels | indent 4 }}
    {{- end }}
  {{- if .Values.tei.service.annotations }}
  annotations:
{{ toYaml .Values.tei.service.annotations | indent 4 }}
  {{- end }}
spec:
  clusterIP: None
  ports:
  - port: {{ .Values.tei.service.port }}
    targetPort: 80
    protocol: TCP
    name: http
  selector:
    app: {{ template "milvus.name" . }}
    release: {{ .Release.Name }}
    component: text-embeddings-inference
{{- end }}
