pull_request_rules:
  - name: add ci-passed when CI passed
    conditions:
      - check-success=lint-test
      - check-success=Broken Links
    actions:
      label:
        toggle:
          - ci-passed
  - name: "Ensure commits follow DCO"
    conditions:
      - "#commits > 0"
      - "body~Signed-off-by:"
    actions:
      comment:
        message: |
          ⚠️ Your PR is missing a `Signed-off-by:` line in at least one commit.
          Please use `git commit -s` to sign your commits.
      dismiss_reviews:
        message: "DCO check failed. Please sign your commits."