apiVersion: v1
description: S3-Interface Libre Object Storage
name: silo
version: 7.0.2
appVersion: RELEASE.2026-09-03T13-18-01Z
keywords:
  - silo
  - storage
  - object-storage
  - s3
  - cluster
home: https://silo.pgsty.com/
icon: https://silo.pgsty.com/img/silo.svg
sources:
- https://github.com/pgsty/silo
maintainers:
- name: Pigsty
  url: https://pigsty.io
