## Enable or disable Milvus Cluster mode
cluster:
  enabled: false
tei:
  enabled: true
  resources:
    requests:
      cpu: "0.1"
      memory: "1Gi"
    limits:
      cpu: "8"
      memory: "16Gi"
volumes: 
- name: custom
  emptyDir: {}
volumeMounts: 
- name: custom
  mountPath: /custom
etcd:
  replicaCount: 1
minio:
  mode: standalone
  resources:
    requests:
      memory: 100Mi
  persistence:
    size: 40Gi
pulsarv3:
  enabled: false
