apiVersion: v1
kind: Service
metadata:
  name: {{ include "tei.fullname" . }}-headless
  labels:
    {{- include "tei.labels" . | nindent 4 }}
spec:
  clusterIP: None
  ports:
  - port: {{ .Values.service.port }}
    targetPort: http
    protocol: TCP
    name: http
  selector:
    {{- include "tei.selectorLabels" . | nindent 4 }}
